[platformio]
src_dir = .
include_dir = include

[env:esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  gin66/FastAccelStepper
  teemuatlut/TMCStepper
extra_scripts =
  pre:scripts/build_metadata.py
build_flags =
  -std=gnu++17
  -DCORE_DEBUG_LEVEL=0
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter =
  +<src/*.cpp>
  +<platforms/esp32_arduino/src/*.cpp>
  -<tests/*>
